# This workflow is a required addition to the higher level 'dependabot.yml' file.
# The dependencies of this project are managed through pip-compile, which is a non-supported ecosystem for dependabot.
# pip-compile uses 'requirements.in' as input, including all top-level packages and outputs 'requirements.txt',
# containing resolved dependencies (including transitive ones)
# Dependabot can detect dependency changes in requirements.txt, but it does not update the entire file.
# This workflow listens for changes in requirements.in and regenerates requirements.txt completely,
# adding the changes to the PR, ensuring no transitive dependencies are missed.

name: Regenerate requirements.txt

on:
  pull_request:
    paths:
      - 'python/requirements.in'

jobs:
  compile:
    if: ${{ github.ref != 'refs/heads/main' && github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Keep version in sync with version used internally

      - name: Install pip-tools
        run: pip install pip-tools

      - name: Compile requirements
        run: pip-compile python/requirements.in --output-file=python/requirements.txt

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          
          git add python/requirements.txt
          git commit -m "Update requirements.txt" || echo "No changes to commit"
          git push
