name: Manual Trigger Workflow

on:
  workflow_dispatch:  # This enables manual triggering

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a command
        run: echo "This workflow was manually triggered!"
